INSERT INTO bookmarks (title, url, created_at)
VALUES ('Google', 'https://www.google.com', CURRENT_TIMESTAMP),
       ('DZone', 'https://dzone.com', CURRENT_TIMESTAMP),
       ('Baeldung', 'https://www.baeldung.com', CURRENT_TIMESTAMP),
       ('Spring', 'https://spring.io', CURRENT_TIMESTAMP),
       ('Java', 'https://www.java.com', CURRENT_TIMESTAMP),
       ('Oracle', 'https://www.oracle.com', CURRENT_TIMESTAMP),
       ('PostgreSQL', 'https://www.postgresql.org', CURRENT_TIMESTAMP),
       ('H2', 'https://www.h2database.com', CURRENT_TIMESTAMP),
       ('H2 Console', 'http://localhost:8080/h2-console', CURRENT_TIMESTAMP),
       ('Swagger', 'http://localhost:8080/swagger-ui.html', CURRENT_TIMESTAMP),
       ('Actuator', 'http://localhost:8080/actuator', CURRENT_TIMESTAMP),
       ('Spring Boot', 'https://spring.io/projects/spring-boot', CURRENT_TIMESTAMP),
       ('Spring Data JPA', 'https://spring.io/projects/spring-data-jpa', CURRENT_TIMESTAMP),
       ('Spring Data JDBC', 'https://spring.io/projects/spring-data-jdbc', CURRENT_TIMESTAMP),
       ('Spring Data R2DBC', 'https://spring.io/projects/spring-data-r2dbc', CURRENT_TIMESTAMP),
       ('Spring Data MongoDB', 'https://spring.io/projects/spring-data-mongodb', CURRENT_TIMESTAMP),
       ('Spring Data Redis', 'https://spring.io/projects/spring-data-redis', CURRENT_TIMESTAMP),
       ('Spring Data Elasticsearch', 'https://spring.io/projects/spring-data-elasticsearch', CURRENT_TIMESTAMP),
       ('Spring Data Neo4j', 'https://spring.io/projects/spring-data-neo4j', CURRENT_TIMESTAMP),
       ('Spring Data Cassandra', 'https://spring.io/projects/spring-data-cassandra', CURRENT_TIMESTAMP),
       ('Spring Data Couchbase', 'https://spring.io/projects/spring-data-couchbase', CURRENT_TIMESTAMP),
       ('Spring Data Solr', 'https://spring.io/projects/spring-data-solr', CURRENT_TIMESTAMP),
       ('Spring Data Gemfire', 'https://spring.io/projects/spring-data-gemfire', CURRENT_TIMESTAMP),
       ('Spring Data Geode', 'https://spring.io/projects/spring-data-geode', CURRENT_TIMESTAMP),
       ('Spring Data KeyValue', 'https://spring.io/projects/spring-data-keyvalue', CURRENT_TIMESTAMP),
       ('Spring Data LDAP', 'https://spring.io/projects/spring-data-ldap', CURRENT_TIMESTAMP),
       ('Spring Data Envers', 'https://spring.io/projects/spring-data-envers', CURRENT_TIMESTAMP),
       ('Spring Data JPA Auditing', 'https://spring.io/projects/spring-data-jpa-auditing', CURRENT_TIMESTAMP),
       ('Spring Data JPA Querydsl', 'https://spring.io/projects/spring-data-jpa-querydsl', CURRENT_TIMESTAMP),
       ('Spring Data JPA Projections', 'https://spring.io/projects/spring-data-jpa-projections', CURRENT_TIMESTAMP),
       ('Spring Data JPA Specifications', 'https://spring.io/projects/spring-data-jpa-specifications', CURRENT_TIMESTAMP),
       ('Spring Data JPA Web Support', 'https://spring.io/projects/spring-data-jpa-web-support', CURRENT_TIMESTAMP),
       ('Spring Data JPA Change Log', 'https://spring.io/projects/spring-data-jpa-change-log', CURRENT_TIMESTAMP),
       ('Spring Data JPA Bulk', 'https://spring.io/projects/spring', CURRENT_TIMESTAMP);