INSERT INTO bookmarks (title, url, created_at)
VALUES ('Google', 'https://www.google.com', now()),
       ('DZone', 'https://dzone.com', now()),
       ('Baeldung', 'https://www.baeldung.com', now()),
       ('Spring', 'https://spring.io', now()),
       ('Java', 'https://www.java.com', now()),
       ('Oracle', 'https://www.oracle.com', now()),
       ('PostgreSQL', 'https://www.postgresql.org', now()),
       ('H2', 'https://www.h2database.com', now()),
       ('H2 Console', 'http://localhost:8080/h2-console', now()),
       ('Swagger', 'http://localhost:8080/swagger-ui.html', now()),
       ('Actuator', 'http://localhost:8080/actuator', now()),
       ('Spring Boot', 'https://spring.io/projects/spring-boot', now()),
       ('Spring Data JPA', 'https://spring.io/projects/spring-data-jpa', now()),
       ('Spring Data JDBC', 'https://spring.io/projects/spring-data-jdbc', now()),
       ('Spring Data R2DBC', 'https://spring.io/projects/spring-data-r2dbc', now()),
       ('Spring Data MongoDB', 'https://spring.io/projects/spring-data-mongodb', now()),
       ('Spring Data Redis', 'https://spring.io/projects/spring-data-redis', now()),
       ('Spring Data Elasticsearch', 'https://spring.io/projects/spring-data-elasticsearch', now()),
       ('Spring Data Neo4j', 'https://spring.io/projects/spring-data-neo4j', now()),
       ('Spring Data Cassandra', 'https://spring.io/projects/spring-data-cassandra', now()),
       ('Spring Data Couchbase', 'https://spring.io/projects/spring-data-couchbase', now()),
       ('Spring Data Solr', 'https://spring.io/projects/spring-data-solr', now()),
       ('Spring Data Gemfire', 'https://spring.io/projects/spring-data-gemfire', now()),
       ('Spring Data Geode', 'https://spring.io/projects/spring-data-geode', now()),
       ('Spring Data KeyValue', 'https://spring.io/projects/spring-data-keyvalue', now()),
       ('Spring Data LDAP', 'https://spring.io/projects/spring-data-ldap', now()),
       ('Spring Data Envers', 'https://spring.io/projects/spring-data-envers', now()),
       ('Spring Data JPA Auditing', 'https://spring.io/projects/spring-data-jpa-auditing', now()),
       ('Spring Data JPA Querydsl', 'https://spring.io/projects/spring-data-jpa-querydsl', now()),
       ('Spring Data JPA Projections', 'https://spring.io/projects/spring-data-jpa-projections', now()),
       ('Spring Data JPA Specifications', 'https://spring.io/projects/spring-data-jpa-specifications', now()),
       ('Spring Data JPA Web Support', 'https://spring.io/projects/spring-data-jpa-web-support', now()),
       ('Spring Data JPA Change Log', 'https://spring.io/projects/spring-data-jpa-change-log', now()),
       ('Spring Data JPA Bulk', 'https://spring.io/projects/spring', now());