# .github/workflows/build.yml

name: CI/CD Pipeline

on:
  push:
    paths:
      - "**"
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]
    paths:
      - "**"

jobs:
  build-kubernetes:
    name: Build and Test Kubernetes Project
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 17 for the project
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Build the project with Maven
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml

      # Step 4: Run tests (if any)
      - name: Run Tests
        run: ./mvnw test

      # Step 5: Build and Publish Docker Image if on the 'master' branch
      - name: Build and Push Docker Image
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t ${DOCKER_USERNAME}/kubernetes-bookmark-api .
          docker push ${DOCKER_USERNAME}/kubernetes-bookmark-api
