# GitHub Actions Workflow to Build a Java Project with Maven and Docker

name: CI/CD Tutorials

on:
  push:
    paths:
      - "kubernetes/**"
    branches: [ "master" ]
  pull_request:
    paths:
      - "kubernetes/**"
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-kubernetes-bookmark-api:
    name: Build and Test Kubernetes Bookmark API
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./kubernetes

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build the project with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Conditionally build and push Docker image if on master branch
      - name: Build and Publish Docker Image
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${DOCKER_USERNAME}/kubernetes-bookmark-api
          docker push ${DOCKER_USERNAME}/kubernetes-bookmark-api

      # (Optional) Update the Maven dependency graph for Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
